name: Generate Snake

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: Avish-Nagiana
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Generated Snake
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -B output
          mv dist/github-contribution-grid-snake.svg ./github-contribution-grid-snake.svg
          git add github-contribution-grid-snake.svg
          git commit -m 'Generate snake animation'
          git push -f origin output

