name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # Add additional permissions if required

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch user data and commit counts
      run: |
        # Initialize variables
        TOTAL_COMMITS=0
        LANGUAGES=""

        # Fetch all repositories (including private ones)
        REPO_LIST=$(curl -s -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
          https://api.github.com/user/repos?per_page=100&visibility=all | jq -r '.[].name')

        echo "Repositories: $REPO_LIST"

        # Iterate over each repository to fetch commit counts and languages
        for REPO in $REPO_LIST; do
          echo "Processing repository: $REPO"

          # Fetch commits for each repository
          COMMITS=$(curl -s -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
            https://api.github.com/repos/Avish-Nagiana/$REPO/commits?per_page=1 | jq -r '.[].sha' | wc -l)
          TOTAL_COMMITS=$((TOTAL_COMMITS + COMMITS))
          
          echo "Commits in $REPO: $COMMITS"

          # Fetch language stats for each repository
          REPO_LANGS=$(curl -s -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
            https://api.github.com/repos/Avish-Nagiana/$REPO/languages | jq -r 'to_entries[] | "\(.key)"')
          
          for LANG in $REPO_LANGS; do
            LANGUAGES=$(echo "$LANGUAGES $LANG" | tr ' ' '\n' | sort | uniq | tr '\n' ' ')
          done
        done

        echo "Total Commits: $TOTAL_COMMITS"
        echo "Languages: $LANGUAGES"

        # Prepare commit count string
        COMMITS_STRING="Total Commits: $TOTAL_COMMITS"
        LANGUAGES_STRING="Languages Used: $LANGUAGES"

        # Update README.md with the total commits and languages
        sed -i "/<total_commits>/r /dev/stdin" README.md <<< "$COMMITS_STRING"
        sed -i "/<languages>/r /dev/stdin" README.md <<< "$LANGUAGES_ST
