name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch user data
      run: |
        # Initialize language usage
        declare -A LANGUAGE_COUNTS

        # List repositories
        REPO_LIST=$(curl -s https://api.github.com/users/Avish-Nagiana/repos?per_page=100 | jq -r '.[].name')

        # Iterate over each repository to fetch language data
        for REPO in $REPO_LIST; do
          # Fetch language data for the repository
          LANGUAGES=$(curl -s https://api.github.com/repos/Avish-Nagiana/$REPO/languages)
          
          # Update language usage
          for LANGUAGE in $(echo "$LANGUAGES" | jq -r 'keys[]'); do
            COUNT=$(echo "$LANGUAGES" | jq -r ".\"$LANGUAGE\"")
            if [[ -n "${LANGUAGE_COUNTS[$LANGUAGE]}" ]]; then
              LANGUAGE_COUNTS[$LANGUAGE]=$((LANGUAGE_COUNTS[$LANGUAGE] + COUNT))
            else
              LANGUAGE_COUNTS[$LANGUAGE]=$COUNT
            fi
          done
        done
        
        # Create language stats string
        LANG_STATS=""
        for LANG in "${!LANGUAGE_COUNTS[@]}"; do
          LANG_STATS+="- $LANG: ${LANGUAGE_COUNTS[$LANG]} bytes\n"
        done
        
        # Update README.md with the language stats
        sed -i "s|<language_stats>|$LANG_STATS|g" README.md
        
        # Commit changes
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add README.md
        git commit -m "Update README with language stats"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
