name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch user data
      run: |
        # Initialize language list
        LANGUAGES=""

        # List repositories
        REPO_LIST=$(curl -s https://api.github.com/users/Avish-Nagiana/repos?per_page=100 | jq -r '.[].name')

        # Iterate over each repository to fetch language data
        for REPO in $REPO_LIST; do
          # Fetch language data for the repository
          LANGUAGES_JSON=$(curl -s https://api.github.com/repos/Avish-Nagiana/$REPO/languages)
          
          # Extract and list languages
          for LANGUAGE in $(echo "$LANGUAGES_JSON" | jq -r 'keys[]'); do
            if ! echo "$LANGUAGES" | grep -q "$LANGUAGE"; then
              LANGUAGES+="- $LANGUAGE\n"
            fi
          done
        done
        
        # Remove duplicate entries and format output
        LANGUAGES=$(echo -e "$LANGUAGES" | sort -u)
        
        # Update README.md with the list of languages
        printf "%s" "$LANGUAGES" > languages.txt
        sed -i "/<language_list>/r languages.txt" README.md
        sed -i "/<language_list>/d" README.md

        # Commit changes
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add README.md
        git commit -m "Update README with language list"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
