name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Update README
      run: |
        # Fetch user data from GitHub API
        curl -s https://api.github.com/users/Avish-Nagiana > stats.json
        
        # Extract values using jq and remove quotes
        REPOS=$(jq -r '.public_repos' stats.json)
        FOLLOWERS=$(jq -r '.followers' stats.json)
        FOLLOWING=$(jq -r '.following' stats.json)
        
        # Update README.md
        sed -i "s|<repo_count>|$REPOS|g" README.md
        sed -i "s|<followers_count>|$FOLLOWERS|g" README.md
        sed -i "s|<following_count>|$FOLLOWING|g" README.md
        
        # Commit changes
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add README.md
        git commit -m "Update README with latest stats"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
