name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # `repo` permission is not needed if you only need to read from private repos

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch user data and commit counts
      run: |
        # Initialize commit count
        TOTAL_COMMITS=0

        # Fetch all repositories (including private ones)
        REPO_LIST=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/user/repos?per_page=100&visibility=all | jq -r '.[].name' || { echo "Failed to fetch repositories"; exit 1; })

        echo "Repositories: $REPO_LIST"

        # Iterate over each repository to fetch commit counts
        for REPO in $REPO_LIST; do
          echo "Processing repository: $REPO"
          
          # Fetch commits for each repository
          COMMITS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/Avish-Nagiana/$REPO/commits?per_page=1 | jq -r '.[].sha' | wc -l || { echo "Failed to fetch commits for $REPO"; continue; })

          echo "Commits in $REPO: $COMMITS"

          # Add to total commits
          TOTAL_COMMITS=$((TOTAL_COMMITS + COMMITS))
        done

        echo "Total Commits: $TOTAL_COMMITS"

        # Prepare commit count string
        COMMITS_STRING="Total Commits: $TOTAL_COMMITS"

        # Update README.md with the total commits
        sed -i "/<total_commits>/r /dev/stdin" README.md <<< "$COMMITS_STRING"
        sed -i "/<total_commits>/d" README.md

        # Commit changes
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add README.md
        git commit -m "Update README with total commits"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
