name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows the workflow to commit changes to the repository

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch and Update Language Icons
      run: |
        # Initialize variables
        LANGUAGES=""

        # Fetch repositories list
        REPO_LIST=$(curl -s -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
          "https://api.github.com/user/repos?per_page=100&visibility=all")

        if [ $? -ne 0 ]; then
          echo "Failed to fetch repository list"
          exit 1
        fi

        # Iterate over each repository
        echo "$REPO_LIST" | jq -r '.[].name' | while read REPO; do
          echo "Processing repository: $REPO"

          # Fetch language stats
          REPO_LANGS=$(curl -s -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
            "https://api.github.com/repos/Avish-Nagiana/$REPO/languages" \
            | jq -r 'to_entries[] | .key')
          
          if [ $? -ne 0 ]; then
            echo "Failed to fetch languages for $REPO"
            continue
          fi

          # Accumulate languages (without duplicates)
          for LANG in $REPO_LANGS; do
            ICON_URL="https://img.shields.io/badge/${LANG}-<color>?style=flat-square"
            LANGUAGES="${LANGUAGES}![${LANG} icon](${ICON_URL}) "
          done
        done

        echo "Languages Icons: $LANGUAGES"

        # Update README.md
        echo "Updating README.md with the latest language icons"
        sed -i "/<languages_icons>/c Languages Used: $LANGUAGES" README.md

        # Commit changes
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add README.md
        git commit -m "Update README with language icons"
        git push
      env:
        PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
