name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows the workflow to commit changes to the repository

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch and Update Stats
      run: |
        # Initialize variables
        TOTAL_COMMITS=0
        LANGUAGES=""

        # Fetch repositories list
        REPO_LIST=$(curl -s -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
          "https://api.github.com/user/repos?per_page=100&visibility=all")

        if [ $? -ne 0 ]; then
          echo "Failed to fetch repository list"
          exit 1
        fi

        # Iterate over each repository
        echo "$REPO_LIST" | jq -r '.[].name' | while read REPO; do
          echo "Processing repository: $REPO"

          # Fetch commits count
          COMMITS=$(curl -s -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
            "https://api.github.com/repos/Avish-Nagiana/$REPO/commits?per_page=1" \
            | jq -r '.[].sha' | wc -l)
          
          if [ $? -ne 0 ]; then
            echo "Failed to fetch commits for $REPO"
            COMMITS=0
          fi

          # Debug: Print commit count
          echo "Commits in $REPO: $COMMITS"

          TOTAL_COMMITS=$((TOTAL_COMMITS + COMMITS))

          # Fetch language stats
          REPO_LANGS=$(curl -s -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
            "https://api.github.com/repos/Avish-Nagiana/$REPO/languages" \
            | jq -r 'to_entries[] | .key')
          
          if [ $? -ne 0 ]; then
            echo "Failed to fetch languages for $REPO"
            continue
          fi

          # Accumulate languages
          for LANG in $REPO_LANGS; do
            LANGUAGES=$(echo "$LANGUAGES $LANG" | tr ' ' '\n' | sort | uniq | tr '\n' ' ')
          done
        done

        echo "Total Commits: $TOTAL_COMMITS"
        echo "Languages: $LANGUAGES"

        # Update README.md
        echo "Updating README.md with the latest stats"
        sed -i "/<total_commits>/c Total Commits: $TOTAL_COMMITS" README.md
        sed -i "/<languages>/c Languages Used: $LANGUAGES" README.md

        # Commit changes
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add README.md
        git commit -m "Update README with total commits and languages"
        git push
      env:
        PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
